#include "EnhKeyUsage.h"

LPCSTR _EnhancedKeyUsageList[] = {
	szOID_PKIX_KP_SERVER_AUTH,
	szOID_PKIX_KP_CLIENT_AUTH,
	szOID_PKIX_KP_CODE_SIGNING,
	szOID_PKIX_KP_EMAIL_PROTECTION,
	szOID_PKIX_KP_TIMESTAMP_SIGNING,
	szOID_PKIX_KP_OCSP_SIGNING,
	szOID_KP_CTL_USAGE_SIGNING,
	szOID_KP_TIME_STAMP_SIGNING,
	szOID_EFS_RECOVERY,
	szOID_NT5_CRYPTO,
	szOID_ROOT_LIST_SIGNER,
	szOID_KP_KEY_RECOVERY,
	szOID_KP_DOCUMENT_SIGNING,
	szOID_KP_LIFETIME_SIGNING,
	szOID_KP_MOBILE_DEVICE_SOFTWARE,
	szOID_KP_CSP_SIGNATURE,
	szOID_KP_FLIGHT_SIGNING,
	szOID_DRM_INDIVIDUALIZATION,
	szOID_LICENSE_SERVER,
	szOID_KP_SMARTCARD_LOGON,
	szOID_KP_KERNEL_MODE_CODE_SIGNING,
	szOID_KP_KERNEL_MODE_TRUSTED_BOOT_SIGNING,
	szOID_REVOKED_LIST_SIGNER,
	szOID_WINDOWS_KITS_SIGNER,
	szOID_WINDOWS_RT_SIGNER,
	szOID_PROTECTED_PROCESS_LIGHT_SIGNER,
	szOID_WINDOWS_TCB_SIGNER,
	szOID_PROTECTED_PROCESS_SIGNER,
	szOID_WINDOWS_THIRD_PARTY_COMPONENT_SIGNER,
	szOID_WINDOWS_SOFTWARE_EXTENSION_SIGNER,
	szOID_WHQL_CRYPTO,
	szOID_OEM_WHQL_CRYPTO
};

LPSTR* EnhancedKeyUsageList = (LPSTR*)(_EnhancedKeyUsageList);
